commit10

diff --git a/.github/workflows/ToolsRustPullRequest.yml b/.github/workflows/ToolsRustPullRequest.yml
--- a/.github/workflows/ToolsRustPullRequest.yml
+++ b/.github/workflows/ToolsRustPullRequest.yml
@@ -35,8 +35,8 @@ jobs :
         run : |
           echo "::set-output name=shouldRun::false"
           # echo "::error"
-          echo "::error file=error::Use keyword "!test" in commit message"
-          # exit 1
+          # echo "::error file=error::Use keyword "!test" in commit message"
+          exit 1
 
   build :
     needs : check
