commit12

diff --git a/.github/workflows/ToolsRustPullRequest.yml b/.github/workflows/ToolsRustPullRequest.yml
--- a/.github/workflows/ToolsRustPullRequest.yml
+++ b/.github/workflows/ToolsRustPullRequest.yml
@@ -1,57 +1,57 @@
-#
-# name : rust_pr
-#
-# on : [ pull_request ]
-#
-# env :
-#   CARGO_TERM_COLOR : always
-#
-# jobs :
-#
-#   continue :
-#     runs-on : ubuntu-latest
-#     outputs :
-#       shouldRun : ${{ steps.run.outputs.shouldRun }}
-#     steps :
-#       - name : List commits on the pull request
-#         run : |
-#           response=$(curl --request GET \
-#           --url 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits' \
-#           --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
-#           --header 'Accept: application/vnd.github.v3+json' \
-#           --header 'Content-Type: application/json')
-#           echo $response > response.json
-#       - name : Get latest commit
-#         id : message
-#         run : |
-#           length=$(jq 'length' response.json)
-#           index=$(($length - 1))
-#           latest_commit=$(jq --argjson index $index '.[$index]' response.json)
-#           latest_commit_message=$(echo "$latest_commit" | jq -r '.commit.message')
-#           echo "::set-output name=message::$latest_commit_message"
-#       - name : Exit with fail
-#         id : run
-#         if : "startsWith( steps.message.outputs.message, 'Merge ' ) || !contains( github.event.head_commit.message, '!build' )"
-#         run : |
-#           echo "::set-output name=shouldRun::false"
-#           # echo "::error"
-#           # echo "::error file=error::Use keyword "!test" in commit message"
-#           exit 1
-#
-#   build :
-#     needs : continue
-#     if : ${{ needs.check.outputs.shouldRun != 'false' }}
-#     uses : Wandalen/wTools/.github/workflows/RustFast.yml@master
-#     with :
-#       manifest_path : './Cargo.toml'
-#
-#   # no_build :
-#   #   needs : check
-#   #   runs-on : ubuntu-latest
-#   #   if : ${{ needs.check.outputs.shouldRun == 'false' }}
-#   #   steps :
-#   #   - name : Exit with fail
-#   #     id : exit
-#   #     run : |
-#   #       echo "::error::!test was not specified"
-#   #       # exit 1
+
+name : rust_pr
+
+on : [ pull_request ]
+
+env :
+  CARGO_TERM_COLOR : always
+
+jobs :
+
+  continue :
+    runs-on : ubuntu-latest
+    outputs :
+      shouldRun : ${{ steps.run.outputs.shouldRun }}
+    steps :
+      - name : List commits on the pull request
+        run : |
+          response=$(curl --request GET \
+          --url 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits' \
+          --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
+          --header 'Accept: application/vnd.github.v3+json' \
+          --header 'Content-Type: application/json')
+          echo $response > response.json
+      - name : Get latest commit
+        id : message
+        run : |
+          length=$(jq 'length' response.json)
+          index=$(($length - 1))
+          latest_commit=$(jq --argjson index $index '.[$index]' response.json)
+          latest_commit_message=$(echo "$latest_commit" | jq -r '.commit.message')
+          echo "::set-output name=message::$latest_commit_message"
+      - name : Exit with fail
+        id : run
+        if : "startsWith( steps.message.outputs.message, 'Merge ' ) || !contains( github.event.head_commit.message, '!build' )"
+        run : |
+          echo "::set-output name=shouldRun::false"
+          # echo "::error"
+          # echo "::error file=error::Use keyword "!test" in commit message"
+          exit 1
+
+  # build :
+  #   needs : continue
+  #   if : ${{ needs.check.outputs.shouldRun != 'false' }}
+  #   uses : Wandalen/wTools/.github/workflows/RustFast.yml@master
+  #   with :
+  #     manifest_path : './Cargo.toml'
+
+  # no_build :
+  #   needs : check
+  #   runs-on : ubuntu-latest
+  #   if : ${{ needs.check.outputs.shouldRun == 'false' }}
+  #   steps :
+  #   - name : Exit with fail
+  #     id : exit
+  #     run : |
+  #       echo "::error::!test was not specified"
+  #       # exit 1
